# Generated by Django 5.2.1 on 2025-05-12 15:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место выполнения привычки')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='Показатель приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность привычки')),
                ('award', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Продолжительность выполнения привычки')),
                ('published', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to='habits.habit', verbose_name='Приятная привычка')),
            ],
            options={
                'verbose_name': ('Привычка',),
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
