# Generated by Django 5.2.1 on 2025-05-13 14:45

import datetime
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.DurationField(default=datetime.timedelta(seconds=120), validators=[habits.validators.execution_time_validator], verbose_name='Продолжительность выполнения привычки'),
        ),
    ]
