# Generated by Django 5.2.1 on 2025-05-14 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='periodicity_of_sending',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность отправки уведомления'),
        ),
    ]
